---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-12.04
  driver:
    network:
    - ["forwarded_port", {guest: 25565, host: 25565}]
#- name: centos-6.5
#  driver:
#    network:
#    - ["forwarded_port", {guest: 25565, host: 25566}]

suites:
- name: default
  data_bags_path: "data_bags"
  run_list:
  - recipe[my_minecraft::default]
  attributes:
