source 'https://rubygems.org'
gem 'chef', '>= 11.14.alpha'
gem 'berkshelf'
gem 'chefspec'
gem 'test-kitchen'
gem 'kitchen-vagrant'
gem 'kitchen-docker'
gem 'busser-bats'
gem 'busser-minitest'
gem 'bundler'
gem 'rspec'
gem 'serverspec'
gem 'chef-zero'
gem 'foodcritic'
gem 'chef-metal'
gem 'chef-metal-fog'
gem 'chef-metal-vagrant'
gem 'chef-metal-docker'
gem 'cheffish'
gem 'knife-container', git: "https://github.com/opscode/knife-container.git"
gem 'knife-spec'
gem 'chefspec'